vodemn/m3_lightmeter

lib/screens/metering/bloc_metering.dart
lib/screens/metering/components/bottom_controls/components/measure_button/widget_button_measure.dart

ML-53 Unsupported operation: Infinity or NaN toInt

---

lib/screens/metering/components/shared/readings_container/components/animated_dialog_picker/components/animated_dialog/widget_dialog_animated.dart

ML-54 `AnimatedDialogState` issues

---

.github/workflows/cd_prod.yml
android/app/build.gradle

As suggested https://github.com/flutter/flutter/issues/32756#issuecomment-846705128 I tried adding abiFilters.

ML-51 Added abiFilters

---

lib/screens/metering/bloc_metering.dart

ML-59 ND filter value is not applied on measure

---

.vscode/launch.json
android/app/build.gradle
android/build.gradle
lib/data/haptics_service.dart
lib/interactors/metering_interactor.dart
lib/screens/metering/bloc_metering.dart
lib/screens/metering/communication/event_communication_metering.dart
lib/screens/metering/communication/state_communication_metering.dart
lib/screens/metering/components/bottom_controls/components/measure_button/widget_button_measure.dart
lib/screens/metering/components/bottom_controls/provider_bottom_controls.dart
lib/screens/metering/components/bottom_controls/widget_bottom_controls.dart
lib/screens/metering/components/camera_container/bloc_container_camera.dart
lib/screens/metering/components/shared/readings_container/components/animated_dialog_picker/widget_picker_dialog_animated.dart
lib/screens/metering/components/shared/readings_container/widget_container_readings.dart
lib/screens/metering/event_metering.dart
lib/screens/metering/flow_metering.dart
lib/screens/metering/screen_metering.dart
lib/screens/metering/state_metering.dart
lib/screens/settings/components/about/components/write_email/widget_list_tile_write_email.dart
pubspec.yaml

ML-58 Metering UX improvements

---

lib/screens/metering/components/camera_container/bloc_container_camera.dart
lib/screens/metering/components/camera_container/event_container_camera.dart

ML-72 buildPreview() was called on a disposed CameraController

---

lib/screens/metering/components/camera_container/bloc_container_camera.dart

ML-74 `CameraContainerBloc` crashes

---

lib/data/shared_prefs_service.dart
lib/providers/stop_type_provider.dart
test/data/shared_prefs_service_test.dart

ML-81 Unsaved fractional stops

---

lib/screens/metering/components/camera_container/widget_container_camera.dart

ML-98 Metering top bar cutout doesn't pass through taps

---

lib/screens/settings/components/metering/components/equipment_profiles/components/equipment_profile_screen/components/equipment_profile_container/components/equipment_list_tiles/components/dialog_range_picker/widget_dialog_picker_range.dart
lib/screens/settings/components/metering/components/equipment_profiles/components/equipment_profile_screen/components/equipment_profile_container/widget_container_equipment_profile.dart
lib/screens/settings/components/metering/components/equipment_profiles/components/equipment_profile_screen/screen_equipment_profile.dart

Equipment profiles issues

---

lib/screens/metering/components/shared/metering_top_bar/shape_top_bar_metering.dart
lib/screens/metering/components/shared/metering_top_bar/widget_top_bar_metering.dart
lib/screens/metering/components/shared/readings_container/components/animated_dialog_picker/components/animated_dialog/widget_dialog_animated.dart

ML-114 Metering container issues

---

iap/lib/src/providers/equipment_profile_provider.dart
lib/l10n/intl_en.arb
lib/l10n/intl_fr.arb
lib/l10n/intl_ru.arb
lib/l10n/intl_zh.arb
lib/screens/metering/components/bottom_controls/widget_bottom_controls.dart
lib/screens/metering/components/camera_container/components/camera_controls/components/exposure_offset_slider/widget_slider_exposure_offset.dart
lib/screens/settings/components/equipment/components/equipment_profiles/components/equipment_profile_screen/components/equipment_profile_container/components/equipment_list_tiles/widget_list_tiles_equipments.dart
lib/screens/settings/components/equipment/components/equipment_profiles/components/equipment_profile_screen/components/equipment_profile_container/widget_container_equipment_profile.dart
lib/screens/settings/components/equipment/components/equipment_profiles/components/equipment_profile_screen/screen_equipment_profile.dart
lib/screens/settings/components/metering/components/calibration/components/calibration_dialog/widget_dialog_calibration.dart
lib/screens/settings/components/shared/dialog_filter/widget_dialog_filter.dart
lib/screens/settings/screen_settings.dart
lib/screens/shared/sliver_screen/screen_sliver.dart

ML-113 Add ability to copy equipment profile

---

lib/data/remote_config_service.dart
lib/providers/remote_config_provider.dart
test/providers/remote_config_provider_test.dart

ML-134 Firebase Remote Config issues

---

lib/screens/settings/components/shared/dialog_filter/widget_dialog_filter.dart
lib/screens/settings/components/shared/dialog_picker/widget_dialog_picker.dart
lib/screens/settings/components/shared/dialog_range_picker/widget_dialog_picker_range.dart

ML-137 Dialogs improvements

---

lib/l10n/intl_en.arb

Fixed typo in reciprocity description

---

android/app/src/main/AndroidManifest.xml
android/app/src/main/res/xml/data_extraction_rules.xml

ML-152 Added data extraction rules

---

.github/workflows/build_apk.yml
.github/workflows/build_ipa.yml
.github/workflows/pr_check.yml
.github/workflows/run_integration_tests.yml
README.md
integration_test/mocks/iap_products_mock.dart
lib/data/models/metering_screen_layout_config.dart
lib/firebase_options.dart
lib/screens/metering/components/camera_container/bloc_container_camera.dart
lib/screens/metering/components/camera_container/components/camera_preview/widget_camera_preview.dart
lib/screens/metering/components/camera_container/widget_container_camera.dart
lib/screens/metering/components/shared/metering_top_bar/widget_top_bar_metering.dart
lib/screens/metering/components/shared/readings_container/components/shared/reading_value_container/widget_container_reading_value.dart
lib/screens/settings/components/metering/components/calibration/components/calibration_dialog/widget_dialog_calibration.dart
lib/screens/settings/components/metering/components/equipment_profiles/components/equipment_profile_screen/screen_equipment_profile.dart
lib/screens/settings/components/shared/dialog_filter/widget_dialog_filter.dart
lib/screens/settings/components/shared/dialog_switch/widget_dialog_switch.dart
pubspec.yaml
test/providers/films_provider_test.dart
test/providers/user_preferences_provider_test.dart
test/screens/metering/components/shared/readings_container/equipment_profile_picker_test.dart
test/screens/metering/components/shared/readings_container/film_picker_test.dart
test_driver/utils/grant_camera_permission.dart

- Migrated to`camera_android_camerax`
Fixes #108

ML-108 First exposure metering seems to be wrong

---

.github/workflows/create_release.yml
iap/lib/src/providers/iap_products_provider.dart
lib/l10n/intl_en.arb
lib/l10n/intl_fr.arb
lib/l10n/intl_ru.arb
lib/l10n/intl_zh.arb
lib/screens/settings/components/about/components/restore_purchases/widget_list_tile_restore_purchases.dart
lib/screens/settings/components/about/widget_settings_section_about.dart
pubspec.yaml

Closes https://github.com/vodemn/m3_lightmeter_iap/issues/7

MLI-7 Manually restore purchases

---

lib/screens/metering/components/camera_container/widget_container_camera.dart
lib/screens/metering/components/shared/exposure_pairs_list/components/exposure_pairs_list_item/widget_item_list_exposure_pairs.dart
pubspec.yaml

ML-189 Auto-downsize exposure pairs items for big display sizes

---

lib/screens/metering/components/camera_container/components/camera_preview/widget_camera_preview.dart

ML-221 Spot Metering only available when Histogram is enabled

---

lib/screens/metering/communication/bloc_communication_metering.dart
lib/screens/metering/communication/event_communication_metering.dart
lib/screens/metering/communication/state_communication_metering.dart
lib/screens/metering/components/camera_container/bloc_container_camera.dart
lib/screens/metering/components/camera_container/components/camera_controls/components/zoom_slider/widget_slider_zoom.dart
lib/screens/metering/components/shared/readings_container/components/equipment_profile_picker/widget_picker_equipment_profiles.dart
test/screens/metering/components/shared/readings_container/equipment_profile_picker_test.dart

ML-218 Changing app resets EV and Zoom values

---

.github/workflows/build_ipa.yml
.github/workflows/run_integration_tests.yml

ML-251 Use Xcode 16.2

---

pubspec.lock
pubspec.yaml

ML-256 App crashes on startup after DB migration

---

.github/workflows/create_release.yml

ML-263 Increment build number before creating a Google Play release
